### PR TITLE
Fix graph margins to make y-axis labels visible

### LINKED ISSUE #18: fix graph y-axis labels
graph margins need to be increased as y-axis labels are not visible entirely (in particular for 3+ digits scales)

### PR DESCRIPTION
**Pull request by simfeld**
Fixes #18

### CODE REVIEW

File: frontend/src/components/Graph/index.js [hunk 1]
```diff
@@ -175,7 +179,7 @@ export class Graph extends React.Component {
 		});
 		
 		// create accrued state lines
-		let lastTime = 0;
+		let lastTime = data[0].time;
```
Comment (simfeld) [inline frontend/src/components/Graph/index.js:182]: Note that here I assume that the first item in the array returned by the `/events` endpoint is always the least recent date (e.g. IED?), and there is at least one item in the array. This is not necessary to fix the margins, just cosmetics. Setting `lastTime = 0;` starts the line somewhere on the far left, which is not what you want, I suppose.

**Comment by nbundi** [comment]
thanks for the fix and pr @simfeld , will be merged into dev. In future, please send prs directly to dev
